### ISSUE TITLE
Relation "Professors" does not exist

### ISSUE THREAD

**Issue by PritishSawant** [vishipayyallore/speaker_series_2020#6]
I am following your first session on XMonkeys360 channel. For the College service project i keep getting following error in screenshot. It says Relation "Professors" does not exist but it is present in my database. I created table using following query 

```
CREATE TABLE Professors(
	ProfessorId int NOT NULL primary key,
	Name varchar(100) NULL,
	Doj timestamp NULL,
	Teaches varchar(100) NULL,
	Salary numeric(18, 2) NULL,
	IsPhd Boolean NULL)
```
I am using postgres instead of my sql. Other than that i have copy pasted your code

![image](https://user-images.githubusercontent.com/24708929/101906062-60ef3500-3bde-11eb-8964-70acce7b14eb.png)

**Comment by vishipayyallore** [comment]
> does not exist but it is present in my database

@PritishSawant 
Good evening. The sample I worked on was using SQL Server. Could you please try this on SQL Server.  In the meanwhile let me try working with PostgreSQL and get back to you.

**Comment by PritishSawant** [comment]
Thanks i will try on sql server

**Comment by PritishSawant** [comment]
![image](https://user-images.githubusercontent.com/24708929/102057823-8d8c9200-3e14-11eb-8520-e8898478b053.png)
I am trying to create a table automatically in my grpc service project by running

dotnet ef migrations add InitialMigration

but the table is not created in the database

**Comment by vishipayyallore** [comment]
@PritishSawant 
Good afternoon. Did you initialize and create the migrations? The same was Database first. I have given the .sql scripts for SQL Server. Many thanks.

**Comment by vishipayyallore** [comment]
@PritishSawant 
I could not spend time this weekend. I am targeting next weekend for trying the sample with PostgreSQL. Many thanks.
